export const GET_CALLS = 'GET_CALLS';
export const GET_CALLS_FAILURE = 'GET_CALLS_FAILURE';
export const GET_CALLS_SUCCESS = 'GET_CALLS_SUCCESS';

export const ICE_CANDIDATE = 'ICE_CANDIDATE';
export const ICE_CANDIDATE_FAILURE = 'ICE_CANDIDATE_FAILURE';
export const ICE_CANDIDATE_SUCCESS = 'ICE_CANDIDATE_SUCCESS';

export const JOIN_CALL = 'JOIN_CALL';
export const JOIN_CALL_FAILURE = 'JOIN_CALL_FAILURE';
export const JOIN_CALL_SUCCESS = 'JOIN_CALL_SUCCESS';

export const LEAVE_CALL = 'LEAVE_CALL';
export const LEAVE_CALL_FAILURE = 'LEAVE_CALL_FAILURE';
export const LEAVE_CALL_SUCCESS = 'LEAVE_CALL_SUCCESS';

export const RENEGOTIATE = 'RENEGOTIATE';
export const RENEGOTIATE_FAILURE = 'RENEGOTIATE_FAILURE';
export const RENEGOTIATE_SUCCESS = 'RENEGOTIATE_SUCCESS';

export const SAVE_NAME = 'SAVE_NAME';

export const SAVE_TRACK = 'SAVE_TRACK';
export const SAVE_TRACK_FAILURE = 'SAVE_TRACK_FAILURE';
export const SAVE_TRACK_SUCCESS = 'SAVE_TRACK_SUCCESS';

export const START_CALL = 'START_CALL';
export const START_CALL_FAILURE = 'START_CALL_FAILURE';
export const START_CALL_SUCCESS = 'START_CALL_SUCCESS';