export const GET_CALLS = 'GET_CALLS';
export const GET_CALLS_FAILURE = 'GET_CALLS_FAILURE';
export const GET_CALLS_SUCCESS = 'GET_CALLS_SUCCESS';

export const JOIN_CALL = 'JOIN_CALL';
export const JOIN_CALL_FAILURE = 'JOIN_CALL_FAILURE';
export const JOIN_CALL_SUCCESS = 'JOIN_CALL_SUCCESS';

export const LEAVE_CALL = 'LEAVE_CALL';
export const LEAVE_CALL_FAILURE = 'LEAVE_CALL_FAILURE';
export const LEAVE_CALL_SUCCESS = 'LEAVE_CALL_SUCCESS';

export const RENEGOTIATE = 'RENEGOTIATE';
export const RENEGOTIATE_FAILURE = 'RENEGOTIATE_FAILURE';
export const RENEGOTIATE_SUCCESS = 'RENEGOTIATE_SUCCESS';

export const SAVE_NAME = 'SAVE_NAME';

export const START_CALL = 'START_CALL';
export const START_CALL_FAILURE = 'START_CALL_FAILURE';
export const START_CALL_SUCCESS = 'START_CALL_SUCCESS';